=== GTsiliki/chipster/src/test/java/session.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="session" type="sessionType"></xs:element>






	<xs:complexType name="sessionType">
		<xs:sequence>
			<xs:element name="operation" type="operationType"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
			<xs:element name="folder" type="folderType"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
			<xs:element name="data" type="dataType"
				maxOccurs="unbounded" minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="format-version" type="xs:int"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="operationType">
		<xs:sequence>
			<xs:element name="id" type="xs:string"></xs:element>
			<xs:element name="finished-time" type="xs:string"></xs:element>
			<xs:element name="description" type="descriptionType"></xs:element>
			<xs:element name="inputs" type="inputsType"></xs:element>
			<xs:element name="outputs" type="outputsType"></xs:element>
			<xs:element name="parameters" type="parametersType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="folderType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"></xs:element>
			<xs:element name="id" type="xs:string"></xs:element>
            <xs:element name="parent" type="xs:string"></xs:element>
            <xs:element name="children" type="childrenType"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="dataType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"></xs:element>
			<xs:element name="id" type="xs:string"></xs:element>
			<xs:element name="folder" type="xs:string"></xs:element>
			<xs:element name="result-of" type="xs:string"></xs:element>
			<xs:element name="storage-type" type="xs:string"></xs:element>
			<xs:element name="url" type="xs:string"></xs:element>
			<xs:element name="cached-url" type="xs:string"></xs:element>
			<xs:element name="links" type="linksType"></xs:element>
			<xs:element name="notes" type="xs:string"></xs:element>
		</xs:sequence>
	</xs:complexType>
	
    <xs:complexType name="descriptionType">
    	<xs:sequence>
    		<xs:element name="name" type="nameType"></xs:element>
    		<xs:element name="type" type="xs:string"></xs:element>
    		<xs:element name="source-code-file" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="nameType">
    	<xs:sequence>
    		<xs:element name="id" type="xs:string"></xs:element>
    		<xs:element name="display-name" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="inputsType">
    	<xs:sequence>
    		<xs:element name="input" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="outputsType">
    	<xs:sequence>
    		<xs:element name="output" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="parametersType">
    	<xs:sequence>
    		<xs:element name="parameter" type="parameterType"
    			maxOccurs="unbounded" minOccurs="0">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="parameterType">
    	<xs:sequence>
    		<xs:element name="name" type="nameType"></xs:element>
    		<xs:element name="value" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="childrenType">
    	<xs:sequence>
    		<xs:element name="child" type="xs:string" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="linksType">
    	<xs:sequence>
    		<xs:element name="link" type="linkType" maxOccurs="unbounded" minOccurs="0"></xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="linkType">
    	<xs:sequence>
    		<xs:element name="target" type="xs:string"></xs:element>
    		<xs:element name="type" type="xs:string"></xs:element>
    	</xs:sequence>
    </xs:complexType>
</xs:schema>

=== GTsiliki/chipster/src/test/java/session.xml
<?xml version="1.0"?>

<session 
	format-version="3" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="session.xsd">

	<!-- Operations -->
	
	<operation>
		<id>oper-0</id>
		<finished-time>2004-09-16T23:59:58.75</finished-time>
		<description>
			<name>
				<id>client-internal-import</id>
				<display-name>Data import in client</display-name>
			</name>			
			<type>internal</type>
			<!-- operation help text here? -->
			<source-code-file></source-code-file>
		</description>
		<inputs>
		</inputs>
		<outputs>
			<output>data-0</output>
		</outputs>
		<parameters>
		</parameters>	
	</operation>

	<operation>
		<id>oper-1</id>
		<finished-time>2004-09-16T23:59:58.75</finished-time>
		<description>
			<name>
				<id>client-internal-import</id>
				<display-name>Data import in client</display-name>
			</name>
			<type>internal</type>
			<source-code-file></source-code-file>
		</description>
		<inputs>
		</inputs>
		<outputs>
			<output>data-1</output>
		</outputs>
		<parameters>
		</parameters>	
	</operation>

	<operation>
		<id>oper-2</id>
		<finished-time>2004-09-17T13:59:58.75</finished-time>
		<description>
			<name>
				<id>norm-illumina.R</id>
				<display-name>Illumina normalisation</display-name>
			</name>
			<type>external</type>
			<source-code-file>source/norm-illumina-1.R</source-code-file>
		</description>
		<inputs>
			<input>data-0</input>
			<input>data-1</input>
		</inputs>
		<outputs>
			<output>data-2</output>
		</outputs>
		<parameters>
			<parameter>
				<name>
					<id>normalize.chips</id>
					<display-name>Normalise chips or genes</display-name>
				</name>
				<value>quantile</value>
			</parameter>	
			<parameter>
				<name>
					<id>beadstudio.version</id>
					<display-name>BeadStudio version of the input file</display-name>
				</name>
				<value>1</value>
			</parameter>	
			<parameter>
				<name>
					<id>chiptype</id>
					<display-name>Chip type of the input file</display-name>
				</name>
				<value>Human-6v1</value>
			</parameter>	
			<parameter>
				<name>
					<id>id.type</id>
					<display-name>ID scheme used in the input file</display-name>
				</name>
				<value>TargetID</value>
			</parameter>	
			<parameter>
				<name>
					<id>produce.flags</id>
					<display-name>Should quality flags be produced also</display-name>
				</name>
				<value>no</value>
			</parameter>
		</parameters>
	</operation>

	<!-- Folders -->

	<folder>
		<name>Datasets</name>
		<id>folder-0</id>
		<parent></parent>
		<children>
		</children>
	</folder>
	
	<folder>
		<name>IlluminaTeratospermiaHuman6v1_BS1</name>
		<id>folder-1</id>
		<parent>folder-0</parent>
		<children>
			<child>data-0</child>
			<child>data-1</child>
			<child>data-2</child>
		</children>
	</folder>


	<!--  Datas -->
	
	<data>
		<name>normalGSM160625 (6729238532412057499).tsv</name>
		<id>data-0</id>
		<folder>folder-1</folder>
		<result-of>oper-0</result-of>
		<storage-type>LOCAL_SESSION</storage-type>
		<url>file:/C:/Documents%20and%20Settings/ekorpela/Desktop/ExampleSessionChipsterV2.cs#file-0</url>
		<cached-url>http://chipster-filebroker.csc.fi:8090/user-data/0c636c43-949d-440b-9c6a-cf8700e70164</cached-url>
		<links>
			<link>
				<target>data-1</target>
				<type>GROUPING</type>
			</link>
		</links>
		<notes></notes>			
	</data>

	<data>
		<name>teratospermialGSM160625 (6729238532412057499).tsv</name>
		<id>data-1</id>
		<folder>folder-1</folder>
		<result-of>oper-1</result-of>
		<storage-type>LOCAL_SESSION</storage-type>
		<url>file:/C:/Documents%20and%20Settings/ekorpela/Desktop/ExampleSessionChipsterV2.cs#file-1</url>
		<cached-url>http://chipster-filebroker.csc.fi:8090/user-data/0c636c43-y523-440b-9c6a-cf8700e70164</cached-url>
		<links>
			<!-- should something be done to links? -->
			<link>
				<target>data-0</target>
				<type>GROUPING</type>
			</link>
		</links>
		<notes></notes>			
	</data>

	<data>
		<name>normalized.tsv</name>
		<id>data-2</id>
		<folder>folder-1</folder>
		<result-of>oper-2</result-of>
		<storage-type>LOCAL_SESSION</storage-type>
		<url>file:/C:/Documents%20and%20Settings/ekorpela/Desktop/ExampleSessionChipsterV2.cs#file-2</url>
		<cached-url>http://chipster-filebroker.csc.fi:8090/user-data/0c636c43-949d-440b-9y58-cf8700e70164</cached-url>
		<links>
			<link>
				<target>data-0</target>
				<type>DERIVATION</type>
			</link>
			<link>
				<target>data-1</target>
				<type>DERIVATION</type>
			</link>
		</links>
		<notes></notes>			
	</data>

</session>

=== GTsiliki/chipster/src/test/java/fi/csc/microarray/session/example/session.xml
<?xml version="1.0"?>

<session 
	format-version="3" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="session.xsd">

	<!-- Folders -->

	<folder>
		<name>Datasets</name>
		<id>folder-0</id>
		<parent></parent>
		<children>
		</children>
	</folder>
	
	<folder>
		<name>IlluminaTeratospermiaHuman6v1_BS1</name>
		<id>folder-1</id>
		<parent>folder-0</parent>
		<children>
		</children>
	</folder>

</session>
